name: Build Program

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout fresh repository
      uses: actions/checkout@v4
    - name: Run Makefile build script
      run: make

    - name: Make directory to archive
      run: mkdir astext_build

    - name: Copy build file(s) to archive directory
      run: cp -vf astext astext_build/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: astext_build_ubuntu_latest
        path: astext_build
