name: Build Program

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make

    - name: create archive
      run: mkdir astext_build

    - name: copy build file(s)
      run: cp -vf astext astext_build/

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: astext_build_ubuntu_latest
        path: astext_build
